POST http://localhost:3000/reports
content-type: application/json

{
  "make": "toyota",
  "model": "EKO",
  "year": 1991,
  "mileage": 10000,
  "price": 2000,
  "lng": 0,
  "lat": 0
}

## Approve an existing report
PATCH http://localhost:3000/reports/5
content-type: application/json

{
  "approved": false
}