### Create user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "test3@test.com",
    "password": "pass1234" 
}


### Get one user
GET  http://localhost:3000/auth/2122222


### Get all user with a given email
GET  http://localhost:3000/auth?email=test@test.com


### Update a user
PATCH http://localhost:3000/auth/22
content-type: application/json

{
    "password": "pass4321"
}


### Remove user per id
DELETE http://localhost:3000/auth/122